# docker compose build file
# for: LinkLeopard
# created in: 2025 by: @jarne

services:
    rustfs:
        image: rustfs/rustfs:1.0.0-alpha.79
        environment:
            RUSTFS_ACCESS_KEY: ${RUSTFS_ACCESS_KEY}
            RUSTFS_SECRET_KEY: ${RUSTFS_SECRET_KEY}
        volumes:
            - rustfs-data:/data
        ports:
            - "9000:9000"
        restart: always
    linkleopard:
        image: ghcr.io/jarne/linkleopard:latest
        depends_on:
            - rustfs
        environment:
            NODE_ENV: production
            DB_FILE_NAME: file:/data/db/local.db
            SESSION_PASSWORD: ${SESSION_PASSWORD}
            APP_LOGIN_PASSWORD: ${APP_LOGIN_PASSWORD}
            NEXT_PUBLIC_S3_ENDPOINT: http://172.17.0.1:9000
            S3_REGION: us-east-1
            S3_ACCESS_KEY: ${RUSTFS_ACCESS_KEY}
            S3_ACCESS_SECRET: ${RUSTFS_SECRET_KEY}
            NEXT_PUBLIC_S3_BUCKET: linkleopard
            NEXT_PUBLIC_S3_FORCE_PATH_STYLE: "true"
        volumes:
            - app-data:/data/db
        ports:
            - "3000:3000"
        restart: always

volumes:
    rustfs-data:
    app-data:
